name: Publish new version

on:
  workflow_dispatch:
    
  schedule:
    - cron: "* * * * *"  # Ejecutar cada minuto

  repository_dispatch:
    types:
      - webhook

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: |
        date +%s > lastUpdate
        git config user.name isaias-alt
        git config user.email cascolucasisaias@gmail.com
        git add lastUpdate
        git diff --quiet && git diff --staged --quiet || git commit -m "[bot] Update blog with latest"
        git push origin main
